# Generated by Django 2.2 on 2019-04-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=20)),
                ('background_image', models.CharField(max_length=20000)),
                ('maps_image', models.CharField(max_length=20000)),
            ],
        ),
    ]
