# Generated by Django 2.2 on 2019-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='amigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='interesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
    ]
