# Generated by Django 2.2 on 2019-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_amigos_interesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='vouchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('decricao', models.CharField(max_length=455)),
                ('foto', models.CharField(max_length=3000)),
            ],
        ),
    ]
