# Generated by Django 2.1.7 on 2019-04-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_vouchers_expirado'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('mensagem', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=3000)),
                ('lidas', models.CharField(max_length=255)),
            ],
        ),
    ]
