# Generated by Django 2.1.7 on 2019-04-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_skin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skin',
            old_name='imagemCapa',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='skin',
            old_name='cor1',
            new_name='black_color',
        ),
        migrations.RenameField(
            model_name='skin',
            old_name='cor10',
            new_name='customBackgroundColor',
        ),
        migrations.RenameField(
            model_name='skin',
            old_name='cor2',
            new_name='customMainColor',
        ),
        migrations.RenameField(
            model_name='skin',
            old_name='cor3',
            new_name='firstFacebookLinear',
        ),
        migrations.RenameField(
            model_name='skin',
            old_name='cor4',
            new_name='firstLinearColor',
        ),
        migrations.RenameField(
            model_name='skin',
            old_name='cor5',
            new_name='secondFacebookLinear',
        ),
        migrations.RenameField(
            model_name='skin',
            old_name='cor6',
            new_name='secondLinearColor',
        ),
        migrations.RenameField(
            model_name='skin',
            old_name='imagemSpash',
            new_name='splash_image',
        ),
        migrations.RenameField(
            model_name='skin',
            old_name='cor7',
            new_name='textFriendsColor',
        ),
        migrations.RenameField(
            model_name='skin',
            old_name='cor8',
            new_name='white_color',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='cor9',
        ),
        migrations.AddField(
            model_name='skin',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skin',
            name='language',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skin',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
