# Generated by Django 2.1.7 on 2019-05-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_auto_20190430_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='testConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=255)),
            ],
        ),
    ]
