# Generated by Django 2.1.7 on 2019-05-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
    ]
